baseUrl = "https://orangetux.nl"
languageCode = "en-us"

[params]
title = "orangetux.nl"
copyright = "This work is licensed under the [Creative Commons Attribution-ShareAlike 3.0 Unported License](http://creativecommons.org/licenses/by-sa/3.0/)."


# You can choose between green, orange, red and blue.
themecolor = "orange"

# Link custom assets relative to /static
favicon   = "favicon.ico"
customCSS = []
customJS  = []

# To provide some metadata for search engines and the about section in the footer
# feel free to add a few information about you and your website.
name = "Auke Willem Oosterhoff"
bio = "embedded Linux engineer - creator of [uModbus](https://github.com/AdvancedClimateSystems/uModbus) and [Goldfish](https://github.com/AdvancedClimateSystems/goldfish)"

# Link your social networks (optional)
github = "orangetux"

# Customize or translate the strings
keepReadingStr = "Keep reading"
backtotopStr = "Back to top"
shareStr = "Share"
pageNotFoundTitle = "404 - Page not found"
